# Generated by Django 6.0.6 on 2026-07-23 18:30

from django.db import migrations, models


def normalize_default_workspace_roles(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    OrganizationMember = apps.get_model('users', 'OrganizationMember')
    WorkspaceMember = apps.get_model('users', 'WorkspaceMember')

    organization = Organization.objects.filter(slug='default-org').first()
    if organization is None:
        return
    members = OrganizationMember.objects.filter(
        organization=organization,
        is_active=True,
    ).order_by('id')
    owner = None
    if organization.created_by_id:
        owner = members.filter(user_id=organization.created_by_id).first()
    owner = owner or members.first()
    if owner is None:
        return

    members.exclude(id=owner.id).update(role='member')
    members.filter(id=owner.id).update(role='owner')
    WorkspaceMember.objects.filter(
        organization_member__organization=organization,
        organization_member__is_active=True,
    ).exclude(organization_member_id=owner.id).update(role='member')
    WorkspaceMember.objects.filter(
        organization_member_id=owner.id,
        is_active=True,
    ).update(role='owner')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_googleaccount_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Egasi'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('member', 'Xodim')], default='member', max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Egasi'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('member', 'Xodim')], default='member', max_length=32),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('owner', 'Egasi'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('member', 'Xodim')], default='member', max_length=32),
        ),
        migrations.RunPython(
            normalize_default_workspace_roles,
            migrations.RunPython.noop,
        ),
    ]
