version: 2
updates:
  - package-ecosystem: pip
    directory: /services/backend
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
