# Generated by Django 6.0.6 on 2026-08-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_organization_organizationmember_workspace_invitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('rank', models.PositiveIntegerField(help_text='1 is the highest position.')),
                ('visibility', models.CharField(choices=[('all', 'Everyone'), ('lower', 'Only this role and lower roles'), ('self', 'Only self')], default='lower', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='users.workspace')),
            ],
            options={
                'ordering': ['rank', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='rbac.jobrole')),
                ('workspace_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_role_assignment', to='users.workspacemember')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobrole',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='rbac_unique_role_name'),
        ),
    ]
