# Generated by Django 6.0.6 on 2026-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='identity_public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='key_algorithm',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
