# Generated by Django 6.0.6 on 2026-07-12 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageattachment_and_more'),
        ('users', '0007_userdevice_lifecycle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='chunk_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='cipher_version',
            field=models.CharField(default='attachment:v1', max_length=64),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='ciphertext_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_key_wrap',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='manifest_sha256',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='plaintext_sha256',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='plaintext_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AttachmentUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('cipher_version', models.CharField(default='attachment:v1', max_length=64)),
                ('plaintext_size', models.BigIntegerField(default=0)),
                ('ciphertext_size', models.BigIntegerField(default=0)),
                ('chunk_size', models.PositiveIntegerField(default=0)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('plaintext_sha256', models.CharField(max_length=128)),
                ('manifest_sha256', models.CharField(max_length=128)),
                ('file_key_wrap', models.TextField()),
                ('blob_storage_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session', to='chat.messageattachment')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_upload_sessions', to='chat.conversation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_upload_sessions', to='users.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentChunkReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_size', models.PositiveIntegerField(default=0)),
                ('ciphertext_sha256', models.CharField(max_length=128)),
                ('storage_key', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_receipts', to='chat.attachmentuploadsession')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('session', 'chunk_index')},
            },
        ),
    ]
