PRIVATE_PREFIXES = ('pqc:v2:',)
GROUP_PREFIXES = ('group:v2:',)
GROUP_ENVELOPE_PREFIX = 'group-wrap:pqc:v2:'
GROUP_ENVELOPE_ALGORITHM = 'group-ml-kem-768-aesgcm-v2'
ATTACHMENT_CIPHER_VERSIONS = ('attachment:v2',)
BACKUP_SCHEMA_REVISION = 2

